language: php
php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - git clone git://github.com/ozh/bookmarkletgen.git

script: phpunit --configuration ./phpunit-travis.xml.dist

notifications:
  email: false
